spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_pa
    username: postgres
    password: Dydd6832_*
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration, org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
